// competitor-2/module-b-2/src/components/Footer.vue
<script setup>
import {RouterLink} from "vue-router";
</script>

<template>
    <footer>
        <div class="left">
            <img src="/img/logo.svg" alt="DineEase logo"><br>
            <a href="#">Terms of Use</a>
            <a href="#">Privacy policy</a>
            <br>
            <a href="tel:+36 30 123 4567">+36 30 123 4567</a>
            <a href="mailto:support@dineease.com">support@dineease.com</a>
            <br>
            <p>© 2024 - All rights reserved</p>
        </div>
        <div class="right">
            <h4>Follow Us</h4>
            <div class="icons">
                <img src="/img/facebook.svg" alt="Facebook">
                <img src="/img/instagram.svg" alt="Instagram">
            </div>
            
        </div>
    </footer>
</template>
    
<style scoped>
    footer {
        background-color: black;
        color: white;

        padding: 4rem;

        display: flex;
        justify-content: space-between;
    }

    .left, .right {
        line-height: 2em;
    }

    a {
        margin-right: 3rem;
    }

    .left img {
        width: 48px;
    }

    .left p {
        opacity: 75%;
    }

    .right {
        margin-right: 200px;
    }

    .icons {
        display: flex;
        gap: 1rem;
        margin-top: 1rem;
    }
</style>

// competitor-1/module-b-1/src/components/Footer.jsx
import logo from "../assets/logo.svg";
import facebook from "../assets/facebook.svg";
import instagram from "../assets/instagram.svg";

export default function Footer() {
  return (
    <footer className="bg-black p-16 flex text-white">
      <div className="w-full">
        <img src={logo} className="mb-4" />
        <ul className="mb-2 flex gap-8">
          <li>Terms of Use</li>
          <li>Privacy Policy</li>
        </ul>
        <ul className="mb-4 flex gap-8">
          <li>
            <a href="tel:+36301234567">+36 30 123 4567</a>
          </li>
          <li>
            <a href="mailto:support@dineease.com">support@dineease.com</a>
          </li>
        </ul>
        <p className="text-gray-400 text-sm">
          &copy; {new Date().getFullYear()} - All rights reserved
        </p>
      </div>
      <div className="shrink-0 w-1/3 md:w-48">
        <p className="mb-4">Follow Us</p>
        <ul className="flex gap-2">
          <li>
            <a href="https://facebook.com" target="_blank">
              <img src={facebook} />
            </a>
          </li>
          <li>
            <a href="https://instagram.com" target="_blank">
              <img src={instagram} />
            </a>
          </li>
        </ul>
      </div>
    </footer>
  );
}
