// competitor-2/module-b-2/src/components/NavBar.vue
<script setup>
import {RouterLink} from "vue-router";
</script>

<template>
    <header>
        <router-link to="/"><img src="/img/logo.svg" alt="DineEase logo"></router-link>
        <nav>
            <a href="/#hero">Overview</a>
            <a href="/#features">Features</a>
            <a href="/#reviews">About Us</a>
            <a href="/#plans">Pricing</a>
        </nav>
        <router-link to="booking" class="button gradient">Book a demo</router-link>
    </header>
</template>
    
<style scoped>
    header {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 2rem;

        position: sticky;
        top: 0;
        background-color: white;
        z-index: 10;

        padding: 2rem 8rem;
    }

    nav {
        display: flex;
        gap: 1rem;
    }

    .button {
        display: none;
    }

    @media screen and (min-width: 768px) {
        nav {
            flex-grow: 1;
        }

        .button {
            display: block;
        }
    }
</style>

// competitor-5/module-b-5/src/components/navbar.jsx
import logo from '../assets/logo.svg'
import {Link} from "react-router-dom";

export default function Navbar() {
    return (
        <header className={'navbar'}>
            <div className={'brand'}>
                <Link to={'/'}><img src={logo} alt="Logo"/></Link>
                <nav>
                    <ul>
                        <li><Link to={'/'} className={'active'}>Overview</Link></li>
                        <li><a href="#">Features</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Pricing</a></li>
                    </ul>
                </nav>
            </div>
            <Link to={'/book-demo'} className={'button-primary'}>Book a demo</Link>
        </header>
    )
}
